apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kuub4p6xf-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kuub4p6xf-go 
  name: kuub4p6xf-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kuub4p6xf-go 
